
services:
   postgres:
     image: postgres:15.1
     volumes:
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
       - postgres_microservice_back:/var/lib/postgresql/data
     environment:
       POSTGRES_USER: google_calendar
       POSTGRES_PASSWORD: google_calendar
       POSTGRES_DB: google_calendar
     ports:
       - 5633:5432
     restart: unless-stopped
 
   back:
     build: google-calendar-back/.
     environment:
       - ENV
     command: npm run start:${ENV:-prod}
     ports:
       - 5500:5500
     depends_on:
       - postgres
   front:
     build: 
       context: google-calendar/.
     labels:
       SERVICE_CHECK_INTERVAL: 10s
     ports:
       - 3040:80
     depends_on:
       - back

 
volumes:
  postgres_microservice_back:
